### PR TITLE
Adding Travis CI

### PR DESCRIPTION
**Pull request by Lucas-C**
This PR adds a shell language linter to this project

The result can be viewed, for my fork of this repo, here: https://travis-ci.org/Lucas-C/pdfjam

There are currently a few warnings detected.
If you think this is a useful addition, I'll ensure they are fixed before you merge this PR.

### CODE REVIEW

**Comment by DavidFirth** [comment]
Thanks, Lucas.  I have to admit, though, that I don't know/understand what any of this is!  Please bear in mind that I am not a professional programmer, not at all, not even close.

I sense that you're offering to help me somehow here, though!  I am very grateful for that --- but I will need to be guided, as I am unsure _how_ to be helped!

Thanks -- David

**Comment by Lucas-C** [comment]
Sure no problem :)

First, a quote from [Travis Ci docs](https://docs.travis-ci.com/user/for-beginners/):

> Continuous Integration is the practice of merging in small code changes frequently - rather than merging in a large change at the end of a development cycle. The goal is to build healthier software by developing and testing in smaller increments. This is where Travis CI comes in.

> As a continuous integration platform, Travis CI supports your development process by automatically building and testing code changes, providing immediate feedback on the success of the change. Travis CI can also automate other parts of your development process by managing deployments and notifications.

Now, Wikipedia definition for a linter: https://en.wikipedia.org/wiki/Lint_(software)

So, I'm suggesting here to:
- perform a static code analysis of `pdfjam` using [`shellcheck`](https://github.com/koalaman/shellcheck/), to identify potential bugs or code style "smells"
- make this process automated for every commit / _pull request_ (PR) submitted to this repo

**Comment by Lucas-C** [comment]
I updated this PR to also execute this project tests as part of the Travis CI pipeline

**Comment by DavidFirth** [comment]
Many thanks, Lucas, for your kind patience in explaining this.  I have a lot to learn!

I should admit that I am nervous, about seeing all the problems that the "linter" will surely find with my amateurish shell script.  But I must be brave...

Just to clarify: Are you suggesting that I should wait, still, for you to do something else _before_ I merge the pull request that you made?

**Comment by Lucas-C** [comment]
Yes, but it's not done ! :)

I have fixed all the minor warnings detected by `shellcheck`.
Those fixes are now included in this PR, and you can review them.

**Comment by Lucas-C** [comment]
About the manual step I mentioned, it corresponds to the 3 first points of this tutorial:
https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci

**Comment by DavidFirth** [comment]
> About the manual step I mentioned, it corresponds to the 3 first points of this tutorial:
> https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci

(A comment here to myself, really.)

I think I have done this, now.  I don't know how to use it.  And probably I have no time to learn about it, before January!  But maybe it will be helpful to me somehow, in due course...let's see.

**Comment by DavidFirth** [comment]
> Yes, but it's now done ! :)
> 
> I have fixed all the minor warnings detected by `shellcheck`.
> Those fixes are now included in this PR, and you can review them.

It seems that the merged changes have (probably) broken something.  Now when I run pdfjam here, I get for example

```
$ pdfjam letters.pdf 
sed: -e expression #1, char 26: extra characters after command
```

--- and the shell just hangs somehow.  I don't know how best to debug this.  If I can't easily find the problem, I might have to undo the merge, and then implement the suggested changes one by one to test incrementally.

**Comment by DavidFirth** [comment]
The problem with the call to 'sed' is now fixed.  It was just a missing space character, on one line.

Phew!

**Comment by Lucas-C** [comment]
Good catch ! Sorry for the bug introduced :)

By the way, you can now see the Travis Ci badge at the top of the README.
While it's green, it means that all the tests & linter are passing on the code of the `master` branch, which is good !

To answer your question about `${pdflatex:-}`: I used this syntax because `shellcheck` complained that this variable was not initialized before being used on line 271. This syntax is detailed in bash manual here: https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html Here it basically means that if `$pdflatex` is undefined, then use an empty string in the `[ -n ]` test.

**Comment by DavidFirth** [comment]
Thanks for explaining all that.  It all makes sense.  I am learning a lot from this.

**Pull request merged**
